# Generated by Django 5.1.1 on 2024-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pre_set1',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pre_set2',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pre_set3',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pre_set4',
            field=models.DurationField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pre_set5',
            field=models.DurationField(blank=True),
        ),
    ]
