# Generated by Django 5.1.1 on 2024-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pre_set1_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='pre_set2_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='pre_set3_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='pre_set4_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='pre_set5_desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
