# Generated by Django 5.1.1 on 2024-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=200)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
