# Generated by Django 5.1.1 on 2024-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_video_genre_video_type_video_video_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thunbnail',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
