# Generated by Django 5.1.1 on 2024-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_video_thunbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='date_in_mils',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
