# Generated by Django 5.1.1 on 2024-10-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_videoprogress_date_in_mils'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoprogress',
            old_name='date_in_mils',
            new_name='date_time',
        ),
    ]
