# Generated by Django 5.1.1 on 2024-10-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='base.series'),
        ),
    ]
